### PR TITLE
Fix icon size in small Android screens and iOS

### PR DESCRIPTION
**Pull request by nfdz**
### Description
We have found an error in the latest versions of the library. The custom icons are huge on Android phones with small screens and on any iOS device.

This problem seems to be related to the Google Maps library for Flutter, I have seen that several developers had this problem and applied a solution similar to this one.

This solution is fully backward compatible and also adds the ability to customize the icon size as desired.

### Screenshots

**Before**

Small screen:
before-small

Large screen:
before-big

**After**

Small screen:
after-small

Large screen:
after-big

### CODE REVIEW

**Comment by jorgecoca** [comment]
> ### Description
> We have found an error in the latest versions of the library. The custom icons are huge on Android phones with small screens and on any iOS device.
> 
> This problem seems to be related to the Google Maps library for Flutter, I have seen that several developers had this problem and applied a solution similar to this one.
> 
> This solution is fully backward compatible and also adds the ability to customize the icon size as desired.

Would you mind adding some screenshots of the before and after? This will help to validate that the fix works

**Comment by nfdz** [comment]
@jorgecoca - I just added the screenshots from the example app.

**Comment by nfdz** [comment]
I see there is a problem with the CI, this PR uses a feature that was added to the SDK in the version **v1.7.8** of Flutter. The CI is failing because it cannot find the method. **Is it possible to update the Flutter SDK version of the CI?**
https://github.com/flutter/engine/blob/fee001c93f25a1e7258e762781a7361f122d29f5/lib/ui/painting.dart#L1657

**Comment by felangel** [comment]
> I see there is a problem with the CI, this PR uses a feature that was added to the SDK in the version **v1.7.8** of Flutter. The CI is failing because it cannot find the method. **Is it possible to update the Flutter SDK version of the CI?**
> https://github.com/flutter/engine/blob/fee001c93f25a1e7258e762781a7361f122d29f5/lib/ui/painting.dart#L1657

https://github.com/bmw-tech/atlas/pull/65

**Comment by dakrawczyk** [comment]
Looks good to me. I see that you're having an analyzer issue since the version of atlas with this parameter isn't published yet. You'll have to resolve this, maybe include the google_atlas changes in a subsequent PR once the Atlas 0.5.2 version is published? 

```  
error • The named parameter 'targetWidth' isn't defined • lib/src/google_atlas.dart:160:7 • undefined_named_parameter
```

**Comment by nfdz** [comment]
@dakrawczyk - It is a problem with the version of Flutter of the CI, it is being updated in this other PR https://github.com/bmw-tech/atlas/pull/65 . On the other hand, I will create a subsequent PR in order to use the new width parameter in the Atlas class.
 
> I see there is a problem with the CI, this PR uses a feature that was added to the SDK in the version **v1.7.8** of Flutter. The CI is failing because it cannot find the method. **Is it possible to update the Flutter SDK version of the CI?**
> https://github.com/flutter/engine/blob/fee001c93f25a1e7258e762781a7361f122d29f5/lib/ui/painting.dart#L1657

**Comment by nfdz** [comment]
@felangel @dakrawczyk @jorgecoca - Re-review please. 
I am not 100% confident about the solution I reached to solve the broken test. I had problems to get done the job of the _FutureBuilder_. Looks like the codec byte reader '_await_' is ignored and I was not able to get the result before the expect statements. Feedback and help are welcome.

**Review by tchabot22 — APPROVED** [review]

**Review by noahmateen — APPROVED** [review]

**Comment by dakrawczyk** [comment]
> @felangel @dakrawczyk @jorgecoca - Re-review please.
> I am not 100% confident about the solution I reached to solve the broken test. I had problems to get done the job of the _FutureBuilder_. Looks like the codec byte reader '_await_' is ignored and I was not able to get the result before the expect statements. Feedback and help are welcome.

Spoke with @nfdz about this, I'd be interested in knowing if there's a cleaner solution to this as well. Since this works I'll approve as it is.

**Review by dakrawczyk — APPROVED** [review]

**Pull request merged**
