### PR TITLE
Platform specific configuration steps added to README (#37)

### PR DESCRIPTION
**Pull request by ezmeev**
#37

### CODE REVIEW

**Review by felangel — APPROVED** [review]
💯

**Comment by jorgecoca** [comment]
@ezmeev seems like the tests are failing on the pipeline (I don't understand how that's possible though...) can you run them locally?

**Review by tchabot22 — APPROVED** [review]

**Review by noahmateen — APPROVED** [review]

**Comment by ezmeev** [comment]
> @ezmeev seems like the tests are failing on the pipeline (I don't understand how that's possible though...) can you run them locally?

I did and test also was failing locally and in master branch. I was trying to fix them and some part I was able to fix (in the same way as Felix did here https://github.com/bmw-tech/atlas/pull/39), but then I stuck with `onTap` handler missing in actual result.

**Comment by felangel** [comment]
> > @ezmeev seems like the tests are failing on the pipeline (I don't understand how that's possible though...) can you run them locally?
> 
> I did and test also was failing locally and in master branch. I was trying to fix them and some part I was able to fix (in the same way as Felix did here #39), but then I stuck with `onTap` handler missing in actual result.

once I merge #39 this should be good to go 👍

**Pull request merged**
