### PR TITLE
Added plugin project for HERE maps

### PR DESCRIPTION
**Pull request by jorgecoca**
This is just the result of running `flutter create`, no SDK or code has been done.

I have created the project:
- Using `swift` for iOS
- Usking `kotlin` for Android

### CODE REVIEW

**Comment by felangel** [comment]
I think the here plugin should be in a separate repo since it can be a standalone flutter plugin similar to google maps. Thoughts?

**Comment by jorgecoca** [comment]
> I think the here plugin should be in a separate repo since it can be a standalone flutter plugin similar to google maps. Thoughts?

Mmmm so would you consider HERE maps then more like a fully fleshed SDK, and then adding a think `atlas` layer here?

**Comment by felangel** [comment]
> > I think the here plugin should be in a separate repo since it can be a standalone flutter plugin similar to google maps. Thoughts?
> 
> Mmmm so would you consider HERE maps then more like a fully fleshed SDK, and then adding a think `atlas` layer here?

Yeah exactly 👍

**Comment by jorgecoca** [comment]
Closing this PR. Moving HERE to a separate repo.

**Pull request closed without merging**
